# Generated by Django 3.1.7 on 2021-03-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parça İsmi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat')),
                ('stock', models.SmallIntegerField(blank=True, null=True, verbose_name='Stok (Zorunlu değil)')),
                ('image', models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Resim (Zorunlu değil)')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True, verbose_name='Ad Soyad')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Telefon (Zorunlu Değil)')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=1, verbose_name='Adet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Parca')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('item_sale_price', models.SmallIntegerField(blank=True, null=True)),
                ('total', models.SmallIntegerField(blank=True, null=True)),
                ('paid_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='Ödenen miktar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi ?')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('orders', models.ManyToManyField(to='main.Order')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='main.person')),
            ],
        ),
    ]
